### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Csokis** [finalburnneo/FBNeo#639]
Hi!

I can't compile on Xubuntu 20.04.1 LTS (SDL2). :( 

> $ make sdl2
Making debug build...

Generating gamelist in src/dep/generated/driverlist.h...
Generating gamelist.txt...
Generating depend file for src/burn/burn.cpp...
Compiling src/burn/burn.cpp...
src/burn/burn.cpp: In function â€˜void BurnDumpLoad_(char*, UINT8*, INT32)â€™:
src/burn/burn.cpp:1050:10: warning: ignoring return value of â€˜size_t fread(void*, size_t, size_t, FILE*)â€™, declared with attribute warn_unused_result [-Wunused-result]
 1050 |     fread(buffer, 1, bufsize, f);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
Compiling src/burner/sdl/run.cpp...
src/burner/sdl/run.cpp: In function â€˜void pause_game()â€™:
src/burner/sdl/run.cpp:348:3: error: â€˜starting_stickâ€™ was not declared in this scope
  348 |   starting_stick = SDL_GetTicks();
      |   ^~~~~~~~~~~~~~
make[1]: *** [makefile.sdl2:544: run.o] Error 1
make: *** [makefile:97: sdl2] Error 2

**Comment by barbudreadmon** [comment]
Seems like a regression from @BeWorld2018's work, i applied a hotfix (https://github.com/finalburnneo/FBNeo/commit/e6c9cf3bc73bbfca3a880c177d2e0e2db499fcf3)

**Comment by Csokis** [comment]
Thank You! Works perfectly! :+1:
